name: Terraform Deploy (Multi-Environment)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod

env:
  TF_VERSION: 1.6.6
  AWS_REGION: us-east-1

jobs:
  terraform:
    name: "Terraform - ${{ inputs.environment }}"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform init -backend-config="backend-main.tf"

      - name: Select or Create Workspace
        run: |
          terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }}

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file=${{ inputs.environment }}.tfvars -out=tfplan

      - name: Approval Gate for Prod
        if: inputs.environment == 'prod'
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: satyapraven   # ⬅️ Replace with GitHub usernames
          minimum-approvals: 1
          issue-title: "Approval needed to deploy to PROD"
          issue-body: "Terraform deployment to PROD requested. Please approve to proceed."
          exclude-workflow-initiator-as-approver: true

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
