name: Terraform CI/CD

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Initialize Terraform with backend config
        run: |
          terraform init -backend-config="backend-${{ github.ref_name }}.tf"

      - name: Validate Terraform configuration
        run: terraform validate

      - name: Select or create workspace
        run: terraform workspace select ${{ github.ref_name }} || terraform workspace new ${{ github.ref_name }}

      - name: Terraform Plan
        run: terraform plan -var-file=${{ github.ref_name }}.tfvars -out=tfplan

      - name: Terraform Apply (requires approval)
        if: github.ref == 'refs/heads/main'
        uses: appleboy/telegram-action@master  # Placeholder for approval gate
        with:
          script: terraform apply -auto-approve tfplan
